version: 2

registries:
  netcracker-npm:
    type: npm-registry
    url: https://npm.pkg.github.com/netcracker
    username: x-access-token
    password: NPM_READ_TOKEN

updates:
  - package-ecosystem: npm
    directory: /apihub-api-diff
    schedule:
      interval: weekly
    registries:
      - netcracker-npm
    groups:
      apihub-api-processor:
        patterns:
          - '@netcracker/qubership-apihub-api-processor'
      apihub-api-diff-dev:
        dependency-type: development
        patterns:
          - '*'
